#include<stdio.h>
#include<math.h>
#include<string.h>
#include<ctype.h>
#include<stdlib.h>
#include <iostream>
#include <vector>
#include <map>
#include <list>
#include <string>
#include <stack>
#include <queue>

using namespace std;


int main()
{

    int a,b,arr[50],arr2[10][3],n,t,num,*p,i,x;
    char c,ch[300],ch1[10][100];
    string ss,sp;
    vector<string>vs;


 ss="madhab"+to_string(3.1416);

 cout<<ss;



     /*        */

    return 0;
}
